# Generated by Django 5.0.7 on 2024-08-03 15:16

import common.utils.file_upload_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_id', models.FileField(upload_to=common.utils.file_upload_paths.suppliers_documents_path, verbose_name='Front side of ID')),
                ('back_id', models.FileField(blank=True, null=True, upload_to=common.utils.file_upload_paths.suppliers_documents_path, verbose_name='Back side of ID')),
                ('tax_card', models.FileField(blank=True, null=True, upload_to=common.utils.file_upload_paths.suppliers_documents_path, verbose_name='Tax card')),
                ('commercial_record', models.FileField(blank=True, null=True, upload_to=common.utils.file_upload_paths.suppliers_documents_path, verbose_name='Commercial Record')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to=common.utils.file_upload_paths.suppliers_documents_path, verbose_name='Bank statement')),
            ],
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='bank_account',
            field=models.CharField(max_length=50, null=True, verbose_name='Bank account'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='electronic_wallet',
            field=models.CharField(max_length=50, null=True, verbose_name='Electronic wallet'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='instabuy_account',
            field=models.CharField(max_length=50, null=True, verbose_name='Instabuy account'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='bank_account',
            field=models.CharField(max_length=50, null=True, verbose_name='Bank account'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='electronic_wallet',
            field=models.CharField(max_length=50, null=True, verbose_name='Electronic wallet'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='entity_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_address', to='account.address', verbose_name='Entity Address'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='instabuy_account',
            field=models.CharField(max_length=50, null=True, verbose_name='Instabuy account'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='documents',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_documents', to='account.supplierdocuments'),
            preserve_default=False,
        ),
    ]
