# Generated by Django 5.0.7 on 2024-08-08 19:38

import common.utils.file_upload_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_buyerprofile_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierdocuments',
            name='back_id',
            field=models.FileField(default=1, upload_to=common.utils.file_upload_paths.suppliers_documents_path, verbose_name='Back side of ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierdocuments',
            name='bank_statement',
            field=models.FileField(default=1, upload_to=common.utils.file_upload_paths.suppliers_documents_path, verbose_name='Bank statement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierdocuments',
            name='commercial_record',
            field=models.FileField(default=1, upload_to=common.utils.file_upload_paths.suppliers_documents_path, verbose_name='Commercial Record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierdocuments',
            name='tax_card',
            field=models.FileField(default=1, upload_to=common.utils.file_upload_paths.suppliers_documents_path, verbose_name='Tax card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='entity_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_address', to='account.address'),
        ),
    ]
