# Generated by Django 5.1 on 2024-08-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_supplierdocuments_back_id_and_more'),
        ('product', '0010_product_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.buyerprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'product')},
            },
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='favorite_products',
            field=models.ManyToManyField(related_name='favorited_by', through='account.Favorite', to='product.product'),
        ),
    ]
