# Generated by Django 5.1 on 2024-08-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandtranslation',
            name='slug',
        ),
    ]
