# Generated by Django 5.1 on 2024-08-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_brandtranslation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandtranslation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
