# Generated by Django 5.1 on 2024-08-10 21:10

import common.validators.image_extension_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories_images/', validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Category Image'),
        ),
    ]
