# Generated by Django 5.1 on 2024-08-10 21:12

import common.utils.file_upload_paths
import common.validators.image_extension_validator
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=common.utils.file_upload_paths.categories_images_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Category Image'),
        ),
    ]
