# Generated by Django 5.1 on 2024-08-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_category_managers_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
