# Generated by Django 5.1 on 2024-08-12 19:37

import common.utils.file_upload_paths
import common.validators.image_extension_validator
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('price_before_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price before discount')),
                ('price_after_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price after discount')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock Quantity')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available ?')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.product_images_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Thumbnail')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.product_images_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.product_images_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.product_images_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.product_images_path, validators=[common.validators.image_extension_validator.image_extension_validator], verbose_name='Image 4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Added On')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edited On')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='Brand')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='Category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
