# Generated by Django 5.1 on 2024-08-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_favorite_unique_together_and_more'),
        ('product', '0012_remove_product_description_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
