# Generated by Django 5.1 on 2024-08-18 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_category_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_pro_slug_33a021_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_before_discount'], name='product_pro_price_b_785511_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_after_discount'], name='product_pro_price_a_0ed106_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_pro_categor_2b9d78_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='product_pro_brand_i_5d76ed_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier'], name='product_pro_supplie_c098a5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created'], name='product_pro_created_998428_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated'], name='product_pro_updated_efcf77_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_before_discount', 'price_after_discount'], name='product_pro_price_b_c89f94_idx'),
        ),
    ]
