# Generated by Django 5.1 on 2024-08-18 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_product_pro_slug_33a021_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(default=0, verbose_name='Total Sold'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_views',
            field=models.IntegerField(default=0, verbose_name='Total Views'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='product_bra_slug_1fd7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='product_cat_slug_93e2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='product_rev_rating_494597_idx'),
        ),
    ]
