# Generated by Django 5.1 on 2024-08-23 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
        ('product', '0019_product_total_sold_product_total_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hero_slider', to='product.category'),
            preserve_default=False,
        ),
    ]
